import type { Metadata } from "next";
import "./globals.css";
import MainLayout from "@/components/layouts/main-layout";
import { Toaster } from "sonner";
import { Rajdhani } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const eduSaFont = Rajdhani({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`antialiased ${eduSaFont.className}`}>
        <MainLayout>{children}</MainLayout>
        <Toaster richColors closeButton position="top-center" />
      </body>
    </html>
  );
};

export default RootLayout;
